import Head from "next/head";
import { AppProps } from "next/dist/shared/lib/router/router";
import "../styles/globals.css";
import React from "react";

export const MyApp = ({ Component, pageProps, router }: AppProps): JSX.Element => {
  return (
    <React.Fragment>
      <Head>
        <title>MyTop - наш лучший топ!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"/>
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
      </Head>
      <Component {...pageProps} />
    </React.Fragment>
  );
}

export default MyApp;
