import Head from "next/head";
import { AppProps } from "next/dist/shared/lib/router/router";
import "../styles/globals.css";
import React from "react";
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';

export const MyApp = ({ Component, pageProps, router }: AppProps): JSX.Element => {
  router.events.on( 'routeChangeComplete', (url: string) => {
    if (typeof window !== 'undefined') {
      ym('hit', url);
    }
  });


  return (
    <React.Fragment>
      <Head>
        <title>MyTop - наш лучший топ!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"/>
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
      </Head>
      <YMInitializer
          accounts={ [] }
          options={ { webvisor: true, defer: true } }
          version='2'
      />
      <Component {...pageProps} />
    </React.Fragment>
  );
}

export default MyApp;
